## Lung cancer using SVM

In [1]:
#importing required library
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
#load the dataset
lg=pd.read_csv("lung_cancer.csv")

In [5]:
lg.head()

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [6]:
#converting categorical data into numerical
from sklearn.preprocessing import LabelEncoder

In [7]:
lr=LabelEncoder()

In [8]:
lg = lg.drop(['Name','Surname'],axis =1)

In [9]:
lg.head()

Age  Smokes  AreaQ  Alkhol  Result
0   35       3      5       4       1
1   27      20      2       5       1
2   30       0      5       2       0
3   28       0      8       1       0
4   68       4      5       6       1

In [10]:
x=lg.iloc[:,:-1].values

In [11]:
x.shape

(119, 4)

In [12]:
y=lg.iloc[:,-1].values

In [13]:
y.shape

(119,)

In [14]:
#split the dataset
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [16]:
x_train.shape

(89, 4)

In [17]:
y_train.shape

(89,)

In [18]:
#import svc 
from sklearn.svm import SVC

In [19]:
s=SVC(kernel="linear",gamma=10,C=1.0)

In [20]:
#fit the model
s.fit(x_train,y_train)

SVC(gamma=10, kernel='linear')

In [21]:
y_pred=s.predict(x_test)

In [22]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0], dtype=int64)

In [23]:
#Evaluation process
from sklearn.metrics import confusion_matrix

In [24]:
cm=confusion_matrix(y_pred,y_test)

In [25]:
cm

array([[20,  0],
       [ 0, 10]], dtype=int64)

In [26]:
from sklearn.metrics import classification_report

In [27]:
clf_report=classification_report(y_pred,y_test)

In [28]:
clf_report

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        20\n           1       1.00      1.00      1.00        10\n\n    accuracy                           1.00        30\n   macro avg       1.00      1.00      1.00        30\nweighted avg       1.00      1.00      1.00        30\n'

In [29]:
#checking accuracy
from sklearn.metrics import accuracy_score

In [30]:
acc=accuracy_score(y_pred,y_test)

In [31]:
acc*100

100.0

In [34]:
#predicting output
new_x=[35,3,5,4]

In [35]:
y_pred=s.predict([new_x])

In [36]:
y_pred

array([1], dtype=int64)